# -*- coding: utf-8 -*-
"""basicsDL.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SddDRUPdHupa5IdE2MpuYjttwUFlnPUo
"""

from tensorflow.keras.datasets import mnist
(trainX, trainy), (testX, testy) = mnist.load_data()

import matplotlib.pyplot as plt
plt.imshow(trainX[0])

(trainX[0].shape, trainy[0])

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import InputLayer, Softmax, Dense, Flatten

model = Sequential()
model.add(InputLayer((28, 28)))
model.add(Flatten())
model.add(Dense(64, activation='relu'))
model.add(Dense(10, 'linear'))

model.add(Softmax())

model.summary()

from tensorflow.keras.losses import CategoricalCrossentropy
model.compile(loss=CategoricalCrossentropy(), optimizer='adam', metrics=['accuracy'])

from tensorflow.keras.utils import to_categorical

trainy = to_categorical(trainy)
trainy.shape

model.fit(trainX, trainy, epochs=5)

testy = to_categorical(testy)

model.evaluate(testX, testy)